services:
  mysql:
#    platform: linux/x86_64 # for Mac M1
    container_name: jimdev_mysql
    image: 'mysql:8.3.0'
    ports:
      - '${DOCKER_MYSQL_PORT:-3307}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - 'mysql-data:/var/lib/mysql'
    networks:
      - backend

  redis:
    image: 'redis:latest'
    container_name: jimdev_redis
    ports:
      - '${DOCKER_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis-data:/data'
    networks:
      - backend

networks:
  backend:
    name: jimdev_network
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
